server.port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pay"
    username: "root"
    password: "rootroot"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 32a0ee4048f2def848a5
            client-secret: 90f70d4e83baad05639b80092b720a7509052133
          google:
            client-id: 804819726324-0u8cjp7one8bqipb0eb8ib2jb4nugsfg.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
logging:
  path: logs
  file:
    max-size: 1MB
    name: ${logging.path}/PayMyBuddy.log
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
    com:
      Pay:
        paymybuddy:
          filter: INFO
          service: INFO
          controller: INFO
          PayMyBuddyApplication: ERROR
  pattern:
    console: "%red(%d{dd/MM/yyyy}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%n%d{dd/MM/yyyy HH:MM:ss} %p %C{1.}%n %m%n"

paymybuddy:
  app:
    secret: "payMyBuddy"
  expires:
    in: 604800

refresh:
  token:
    expires:
      in: 604800
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/payTest"
    username: "root"
    password: "rootroot"
spring.config.activate.on-profile: test
logging:
  path: logs
  file:
    max-size: 1MB
    name: ${logging.path}/PayMyBuddyTest.log
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      boot:
        StartupInfoLogger: ERROR
    com:
      Pay:
        paymybuddy:
          filter: INFO
          service: INFO
          controller: INFO
          PayMyBuddyApplication: ERROR
  pattern:
    console: "%red(%d{dd/MM/yyyy}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%n%d{dd/MM/yyyy HH:MM:ss} %p %C{1.}%n %m%n"
---

management.endpoints.web.exposure.include: "*"

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: "*"